#!/usr/bin/env bash
"vendor/wp-cli/wp-cli/bin/wp" plugin deactivate --network --all
"vendor/wp-cli/wp-cli/bin/wp" plugin activate --network \
adminimize \
advanced-custom-fields \
author-chat \
cms-tree-page-view \
disable-new-user-notifications \
events-manager \
firebase-notifications \
ig-cms-tree-page-view-extensions \
ig-content-loader-base \
ig-content-loader-instance \
ig-customize-editor-integreat \
ig-customize-login-integreat \
ig-enhanced-help-menu \
ig-extras \
ig-login-redirect-pages \
ig-menu-help \
ig-pdf-creator-lite-font-extension \
ig-plugin-adjustment \
ig-project-user-roles \
ig-remove-403-forbidden \
ig-separate-disclaimer \
ig-settings \
ig-simplify-ui \
ig-text-dir \
ig-wp-api-extensions \
ig-wpml-lock-media-checkboxes \
ig-hide-preview-button \
ig-dashboard-widget \
multisite-clone-duplicator \
pdf-creator-lite \
simple-page-ordering \
sitepress-multilingual-cms \
tinymce-advanced \
use-google-libraries \
user-role-editor \
wpml-media-translation \
wpml-translation-management \
wp-rtl \
wp-sync-db-1.5
