<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WPML_Auto_Loader' => $vendorDir . '/wpml/commons/src/wpml-auto-loader.php',
    'WPML_Twig_WP_Plugin_Extension' => $vendorDir . '/wpml/commons/src/twig-extensions/wpml-twig-wp-plugin-extension.php',
);
